capcodigital/global-challenge

app/components/common/counter.component.js
app/components/common/index.js
app/components/common/list.component.js
app/components/dashboard/dashboardold.component.js
app/components/dashboard/style.scss
package-lock.json
package.json
yarn.lock

Signed commit of ticket for CGC-40: Create Teams Dashboard with multiple panels/component sections to show different leaderboards/statistics - work done by avrx.

GCG-40: main view structure complete

---

.dockerignore
.gitignore
Dockerfile
config/keys/databaseConfigCapco.txt
config/keys/sessionKeyCapco.txt
server/controllers/fitbit.controller.js
server/controllers/strava.controller.js
server/services/cit.service.js
server/services/fitbit.service.js

Dockerfile for containerising the application
Fitbit, Strava and CIT check first for the key in environment variables and then try to read a file - compatible both for local development and for running on the cluster.

CGC-28 env vars support added

---

app/components/common/MapUK.component.js
app/components/common/style.scss
app/components/dashboard/TeamDashboard.component.js
app/components/dashboard/dashboard.component.js
app/components/header/header.component.js
app/components/header/style.scss

**Added:**
- waypoints to Map component
- popup to display team name, distance, position + styling (I had to do inline styling and couldn't remove the arrow, for some reason it broke all the other styles on every other page when I put it in any scss file)
- latlng bounds for map
- zoom on team on loading teams view page
- donate and register buttons to header

CGC-44 map improvements

---

app/components/app.js
app/components/dashboard/actions.js
app/components/register/register.component.js
app/components/teams/actions.js
app/components/teams/teams.component.js
app/messages/messages_EN.json
package-lock.json
package.json
server/config/env/all.js
server/controllers/fitbit.controller.js
server/controllers/strava.controller.js
server/controllers/teams.controller.js
server/models/team.model.js
server/models/user.model.js
server/services/mail.service.js
yarn.lock

Made a start on email and team limit functionality plus updates for the demo on Friday.

Cgc 14 user email during registration

---

app/components/common/TeamLeaderboardTable.component.js
app/components/common/TeamSportsLeaderboardTable.component.js
app/components/common/style.scss
app/components/dashboard/TeamDashboard.component.js
app/components/dashboard/dashboard.component.js
app/components/dashboard/selectors.js
app/components/dashboard/style.scss

**Added** 
- converted data to total distance and cycling distance in main/sports leaderboards
- tooltips to show actual data for cycling on teams page
- fix for overall distance animation

Cgc 61 converted data

---

app/components/dashboard/TeamDashboard.component.js
app/components/dashboard/dashboard.component.js
config/webpack.base.babel.js

env vars exposed to frontend

---

Dockerfile
app/components/dashboard/actions.js
app/components/register/register.component.js
app/components/teams/actions.js
app/components/teams/teams.component.js
server/config/env/production.js
server/config/models.js
server/controllers/fitbit.controller.js
server/controllers/strava.controller.js
server/controllers/teams.controller.js
server/index.js
server/util/port.js

All of the changes here are the same as in CGC-28-gcp. I suggest this PR gets merged rather than the other one as we know this one is stable and it has latest changes from master + consistent changes to connect to the backend on the cluster.

replicated HTTPS to HTTP changes

---

server/controllers/teams.controller.js

Fix homepage breaking on team creation.

Missing activities fix

---

config/webpack.base.babel.js

add fitbit and strava client ids to webpack

add fitbit and strava client ids to webpack

---

app/components/teams/teams.component.js
package.json
server/config/env/all.js
server/controllers/capco.controller.js
server/controllers/challenges.controller.js
server/controllers/fitbit.controller.js
server/controllers/levels.controller.js
server/controllers/locations.controller.js
server/controllers/strava.controller.js
server/controllers/teams.controller.js
server/controllers/users.controller.js
server/middlewares/addDevMiddlewares.js
server/middlewares/addProdMiddlewares.js
server/routes/users.route.js
server/services/mail.service.js
yarn.lock

Cgc 112 uk challenge backend

---

package-lock.json
package.json
yarn.lock

Vulnerabilities

---

Dockerfile

Updated the node version in docker file

---

.github/workflows/build_push_deploy.yml

Added GitAction pipeline to build, publish and deploy the change in Cloud Run

Added pipeline to push image and deploy cloud run service 

---

app/components/register/register.component.js
server/controllers/capco.controller.js
server/controllers/fitbit.controller.js
server/controllers/strava.controller.js
server/controllers/teams.controller.js

Switch from Capco username to email

---

app/components/SidebarMenu/style.scss
app/components/global/common/style.scss
app/components/global/dashboard/dashboardGlobal.component.js
app/components/global/dashboard/style.scss
app/components/global/leaderboardTabs/leaderboardTabs.component.js
app/components/global/tabs/style.scss
app/components/header/style.scss
app/components/style.scss
app/components/uk/dashboard/style.scss
app/components/uk/tabs/style.scss

Removing teams tab and rowing

---

app/components/global/leaderboardTabs/leaderboardTabs.component.js
app/components/header/style.scss

Update landing page leaderboard

---

server/controllers/strava.controller.js

To see what is the Capco ID which cannot be found.

Improves logging, a little bit.

---

app/components/global/common/CountDown.js
app/components/uk/common/Countdown.component.js
server/controllers/fitbit.controller.js
server/controllers/levels.controller.js
server/controllers/locations.controller.js
server/controllers/strava.controller.js

Minor fixes to get trial up and running

---

app/components/HowTo/SetupInstructions.component.js
app/components/HowTo/StravaSetupInstructions.component.js
server/controllers/users.controller.js
server/middlewares/addDevMiddlewares.js
server/middlewares/addProdMiddlewares.js

Wording fix and extra delete user endpoint

---

app/components/about/AboutPage.component.js
app/components/homepage/homepage.component.js
app/messages/messages_EN.json
server/models/user.model.js

Wording, spelling and database unique constraint fixes

---

server/controllers/fitbit.controller.js
server/controllers/strava.controller.js

Email wording update

---

app/components/global/dashboard/constants.js

Turning off conversion factor to show real progress.

---

app/components/global/common/TeamLeaderboardTable.component.js
app/components/global/common/TeamSportsLeaderboardTable.component.js
app/components/global/dashboard/dashboardGlobal.component.js
app/components/global/dashboard/style.scss

*Add search button to improve search field responsiveness.*
https://github.com/capcodigital/global-challenge/assets/92087295/6c7e13b6-1509-49e8-8a91-f69804f931cd

add search button and improve search

---

app/components/global/dashboard/constants.js

Corrected distances

---

server/controllers/strava.controller.js

Increase Strava page limit

---

app/components/about/AboutPage.component.js
app/components/global/common/CountDown.js
app/components/global/dashboard/constants.js

Fudging the end distance to match the challenge target

---

server/controllers/fitbit.controller.js
server/controllers/strava.controller.js

Turn off sync 9am Monday so challenge result is "frozen"

---

package-lock.json
package.json

Remove lint-staged as it is is no longer supported by older node versions.

remove node unsuported dependency

---

app/components/global/dashboard/constants.js
app/components/global/map/map.component.js

https://ilabs-capco.atlassian.net/browse/CGC-117
This PR is to add additional points for the live route, this means that users can see a more accurate view of how far along they are in the total distance covered to date.
The path is no longer arched, in order to have multiple touch points the path is now a straight line.
OLD SCREEN 
NEW SCREEN

CGC-117-Enhance Global Map

---

app/components/about/AboutPage.component.js
app/components/global/common/CountDown.js
server/controllers/fitbit.controller.js
server/controllers/levels.controller.js
server/controllers/strava.controller.js
server/controllers/teams.controller.js

Aligning dates with the database for a Prod test

---

server/controllers/fitbit.controller.js

Fix promise issues with FitBit stats save

---

app/components/about/AboutPage.component.js
app/components/homepage/homepage.component.js

update fundraising link

---

server/controllers/fitbit.controller.js
server/controllers/strava.controller.js

Email date fix

---

app/components/homepage/homepage.component.js

Updated fund matching note

---

app/components/global/common/CountryLeaderboardTable.component.js

remove NAN error

---

app/components/global/common/CountDown.js

counter counts up not down

---

server/controllers/fitbit.controller.js
server/controllers/strava.controller.js

Email updates

---

app/components/global/dashboard/constants.js

added hyderabad and chennai

---

app/components/global/common/CountryLeaderboardTable.component.js
app/components/global/dashboard/dashboardGlobal.component.js

updated distance fields

---

app/components/global/common/MenuFilter.component.js
app/components/global/common/PersonalLeaderboard.component.js
app/components/global/dashboard/constants.js
app/components/global/dashboard/selectors.js

update city list

---

app/components/global/common/PersonalLeaderboard.component.js

display totalDistanceConverted personal view

---

app/components/faq/questionData.js
app/components/footer/footer.component.js
server/controllers/strava.controller.js

Replaced old ms teams email

---

server/controllers/fitbit.controller.js

Logging improvements

---

server/controllers/strava.controller.js

Reverting earlier change

---

server/controllers/countries.controller.js
server/controllers/fitbit.controller.js
server/controllers/locations.controller.js
server/controllers/strava.controller.js

Stop sync now challenge has finished
